apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onescm.fullname" . }}
  labels:
    {{- include "onescm.labels" . | nindent 4 }}
data:
  PORT: "3000"
  DATA_DIR: /data
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- range $k, $v := .Values.extraEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- if .Values.tracing.enabled }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.tracing.endpoint | quote }}
  OTEL_SERVICE_NAME: {{ .Values.tracing.serviceName | quote }}
  {{- end }}
