apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onescm.fullname" . }}-api
  labels:
    {{- include "onescm.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "onescm.selector" (dict "root" . "component" "api") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "onescm.selector" (dict "root" . "component" "api") | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- include "onescm.pod" (dict "root" . "component" "api" "worker" false "resources" .Values.api.resources) | nindent 6 }}
